version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Mariam1+
      MYSQL_DATABASE: audit_db
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql

  server:
    build: ./server
    restart: always
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DB_HOST: 192.168.1.7
      DB_PORT: 3306
      DB_USER: dockeruser
      DB_PASSWORD: arman2001+
      DB_NAME: audit_db
      SECRET_KEY: arman2001
      JWT_ACCESS_SECRET: arman2001
      JWT_REFRESH_SECRET: 12345678
      CLIENT_URL: http://localhost:8080
    depends_on:
      - db

  client:
    build: ./client
    restart: always
    ports:
      - "8080:8080"
    mem_limit: 512m
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - server
volumes:
  db: